apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{"storageclass.kubernetes.io/is-default-class":"true","storageclass.kubesphere.io/support-snapshot":"false"},"creationTimestamp":"2021-04-07T08:14:34Z","managedFields":[{"apiVersion":"storage.k8s.io/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{},"f:storageclass.kubernetes.io/is-default-class":{}}},"f:parameters":{".":{},"f:archiveOnDelete":{}},"f:provisioner":{},"f:reclaimPolicy":{},"f:volumeBindingMode":{}},"manager":"kubectl-client-side-apply","operation":"Update","time":"2021-04-07T08:14:34Z"},{"apiVersion":"storage.k8s.io/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{"f:storageclass.kubesphere.io/support-snapshot":{}}}},"manager":"controller-manager","operation":"Update","time":"2021-04-22T10:01:10Z"}],"name":"nfs-storageclass","resourceVersion":"3663236","selfLink":"/apis/storage.k8s.io/v1/storageclasses/nfs-storageclass","uid":"ce551a7c-6484-4459-84d7-4747684408da"},"parameters":{"archiveOnDelete":"false"},"provisioner":"nfs-provisioner","reclaimPolicy":"Delete","volumeBindingMode":"Immediate"}
    storageclass.kubernetes.io/is-default-class: "true"
    storageclass.kubesphere.io/support-snapshot: "false"
  creationTimestamp: "2021-04-07T08:14:34Z"
  managedFields:
  - apiVersion: storage.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:storageclass.kubernetes.io/is-default-class: {}
      f:parameters:
        .: {}
        f:archiveOnDelete: {}
      f:provisioner: {}
      f:reclaimPolicy: {}
      f:volumeBindingMode: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-04-07T08:14:34Z"
  - apiVersion: storage.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:storageclass.kubesphere.io/support-snapshot: {}
    manager: controller-manager
    operation: Update
    time: "2021-04-22T10:01:10Z"
  - apiVersion: storage.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:kubectl.kubernetes.io/last-applied-configuration: {}
    manager: kubectl
    operation: Update
    time: "2021-06-22T06:35:36Z"
  name: nfs-storageclass
  resourceVersion: "23136768"
  selfLink: /apis/storage.k8s.io/v1/storageclasses/nfs-storageclass
  uid: ce551a7c-6484-4459-84d7-4747684408da
parameters:
  archiveOnDelete: "true"
provisioner: nfs-provisioner
reclaimPolicy: Delete
volumeBindingMode: Immediate
