{{- if .Values.psp.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels: {{- include "nexus.labels" . | nindent 4 }}
  {{- with .Values.nexus.extraLabels }}
    {{ toYaml . | indent 4 }}
  {{- end }}
  name: {{ template "nexus.name" . }}-psp-use
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "nexus.name" . }}-psp-use
subjects:
- kind: ServiceAccount
  name: {{ include "nexus.serviceAccountName" . }}
{{- end -}}