{{- if .Values.psp.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels: {{- include "nexus.labels" . | nindent 4 }}
  {{- with .Values.nexus.extraLabels }}
    {{ toYaml . | indent 4 }}
  {{- end }}
  name: {{ template "nexus.name" . }}-psp-use
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - {{ template "nexus.name" . }}
  verbs:
  - use
{{- end -}}