# Default values for dex.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Number of replicas (pods) to launch.
replicaCount: 1

image:
  # -- Name of the image repository to pull the container image from.
  repository: ghcr.io/dexidp/dex

  # -- [Image pull policy](https://kubernetes.io/docs/concepts/containers/images/#updating-images) for updating already existing images on a node.
  pullPolicy: IfNotPresent

  # -- Image tag override for the default value (chart appVersion).
  tag: ""

# -- Reference to one or more secrets to be used when [pulling images](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-pod-that-uses-your-secret) (from private registries).
imagePullSecrets: []

# -- A name in place of the chart name for `app:` labels.
nameOverride: ""

# -- A name to substitute for the full names of resources.
fullnameOverride: ""

# -- A list of hosts and IPs that will be injected into the pod's hosts file if specified.
# See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#hostname-and-name-resolution)
hostAliases: []

https:
  # -- Enable the HTTPS endpoint.
  enabled: false

grpc:
  # -- Enable the gRPC endpoint.
  # Read more in the [documentation](https://dexidp.io/docs/api/).
  enabled: false

configSecret:
  # -- Enable creating a secret from the values passed to `config`.
  # If set to false, name must point to an existing secret.
  create: true

  # -- The name of the secret to mount as configuration in the pod.
  # If not set and create is true, a name is generated using the fullname template.
  # Must point to secret that contains at least a `config.yaml` key.
  name: ""

# -- Application configuration.
# See the [official documentation](https://dexidp.io/docs/).
config:
  # Set it to a valid URL
  issuer: https://dex.k3.acornsoft.io/dex

  # See https://dexidp.io/docs/storage/ for more options
  # storage:
  #   type: memory
  storage:
    type: kubernetes
    config:
      inCluster: true

  # Enable at least one connector
  # See https://dexidp.io/docs/connectors/ for more options
  enablePasswordDB: true

  web:
    http: 0.0.0.0:5556

  connectors:
    - type: gitlab
      id: gitlab
      name: GitLab
      config:
        baseURL: https://git.k3.acornsoft.io
        clientID: abc9d9061db64a77a8c45ecf315ac92557f6faf03248cb3995cd9232b72749ce
        clientSecret: b076c80e5a1b6a15ecc2f174a963cdc9acd23a5b986ce3ee8f2a3587a21bc6f2
        redirectURI: https://dex.k3.acornsoft.io/dex/callback
        #groups:
        #- open
        useLoginAsID: false
    # - type: github
    #   id: github
    #   name: Github
    #   config:
    #     clientID: 12a6d94647d122abf193
    #     clientSecret: 2394e3a732fe4d9ecdc5717286937f9b13f26ef5
    #     redirectURI: https://dex.k3.acornsoft.io/dex/callback
    #     #groups:
    #     #- open
    #     useLoginAsID: false
    # - type: google
    #   id: google
    #   name: Google
    #   config:
    #     clientID: 968321444210-v8sd4e05lhmtdes5livublf2vrd4pr46.apps.googleusercontent.com
    #     clientSecret: X-u_fioJQ0f3tJL_LdAGuI-Q
    #     redirectURI: https://dex.k3.acornsoft.io/dex/callback
    #     #groups:
    #     #- open
    #     useLoginAsID: false

  oauth2:
    skipApprovalScreen: true

  staticClients:
  - id: example-app
    redirectURIs:
    - 'https://dex.k3.acornsoft.io/callback'
    name: 'Example App'
    secret: ZXhhbXBsZS1hcHAtc2VjcmV0

  - id: kiali-client
    redirectURIs:
    - 'https://kiali.k3.acornsoft.io/kiali'
    name: 'Kiali App'
    secret: ZXhhbXBsZS1hcHAtc2VjcmV0

  staticPasswords:
  - email: "admin@example.com"
    # bcrypt hash of the string "password"
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
    username: "admin"
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"

# -- Additional storage [volumes](https://kubernetes.io/docs/concepts/storage/volumes/).
# See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#volumes-1) for details.
volumes: []

# -- Additional [volume mounts](https://kubernetes.io/docs/tasks/configure-pod-container/configure-volume-storage/).
# See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#volumes-1) for details.
volumeMounts: []

# -- Additional environment variables mounted from [secrets](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables) or [config maps](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#configure-all-key-value-pairs-in-a-configmap-as-container-environment-variables).
# See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#environment-variables) for details.
envFrom: []

# -- Additional environment variables passed directly to containers.
# See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#environment-variables) for details.
env: {}

serviceAccount:
  # -- Enable service account creation.
  create: true

  # -- Annotations to be added to the service account.
  annotations: {}

  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template.
  name: ""

rbac:
  # -- Specifies whether RBAC resources should be created.
  # If disabled, the operator is responsible for creating the necessary resources based on the templates.
  create: true

# -- Annotations to be added to pods.
podAnnotations: {}

podDisruptionBudget:
  # -- Enable a [pod distruption budget](https://kubernetes.io/docs/tasks/run-application/configure-pdb/) to help dealing with [disruptions](https://kubernetes.io/docs/concepts/workloads/pods/disruptions/).
  # It is **highly recommended** for webhooks as disruptions can prevent launching new pods.
  enabled: false

  # -- (int/percentage) Number or percentage of pods that must remain available.
  minAvailable:

  # -- (int/percentage) Number or percentage of pods that can be unavailable.
  maxUnavailable:

# -- Specify a priority class name to set [pod priority](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#pod-priority).
priorityClassName: ""

# -- Pod [security context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod).
# See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#security-context) for details.
podSecurityContext: {}
  # fsGroup: 2000

# -- Container [security context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container).
# See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#security-context-1) for details.
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  # -- Annotations to be added to the service.
  annotations: {}

  # -- Kubernetes [service type](https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types).
  type: ClusterIP

  ports:
    http:
      # -- HTTP service port
      port: 5556

      # -- (int) HTTP node port (when applicable)
      nodePort:

    https:
      # -- HTTPS service port
      port: 5554

      # -- (int) HTTPS node port (when applicable)
      nodePort:

    grpc:
      # -- gRPC service port
      port: 5557

      # -- (int) gRPC node port (when applicable)
      nodePort:

ingress:
  # -- Enable [ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/).
  enabled: true

  # -- Ingress [class name](https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class).
  className: ""

  # -- Annotations to be added to the ingress.
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 50000m

  # -- Ingress host configuration.
  # @default -- See [values.yaml](values.yaml).
  hosts:
    - host: dex.k3.acornsoft.io
      paths:
        - path: /dex
          pathType: Prefix
          fullName: dex
          svcPort: 5556
        - path: /
          pathType: Prefix
          fullName: kid
          svcPort: 5555

  # -- Ingress TLS configuration.
  # @default -- See [values.yaml](values.yaml).
  tls:
   - secretName: tls-acornsoft-star
     hosts:
       - dex.k3.acornsoft.io

# -- Container resource [requests and limits](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/).
# See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#resources) for details.
# @default -- No requests or limits.
resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

# -- Autoscaling configuration (see [values.yaml](values.yaml) for details).
# @default -- Disabled by default.
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# -- [Node selector](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector) configuration.
nodeSelector: {}

# -- [Tolerations](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/) for node taints.
# See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#scheduling) for details.
tolerations: []

# -- [Affinity](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity) configuration.
# See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#scheduling) for details.
affinity: {}
