---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: cocktail-addon
  labels:
    k8s-app: fluent-bit
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit
  labels:
    k8s-app: fluent-bit
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit
  labels:
    k8s-app: fluent-bit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit
subjects:
- kind: ServiceAccount
  name: fluent-bit
  namespace: cocktail-addon
---
apiVersion: v1
kind: Secret
metadata:
  name: fluent-bit
  namespace: cocktail-addon
type: Opaque
data:
  es-username: YWRtaW4=
  es-password: YWRtaW4=
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMwRENDQWJpZ0F3SUJBZ0lVY1pJbUhZZ0E2UHhUVFRtZ3RQNjFtRHh1S2hVd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0VURVBNQTBHQTFVRUF3d0dVbTl2ZEVOQk1CNFhEVEl3TURneU5qQXlNekF3T1ZvWERUTXdNRGd5TkRBeQpNekF3T1Zvd0VURVBNQTBHQTFVRUF3d0dVbTl2ZEVOQk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBCk1JSUJDZ0tDQVFFQXdmeGZXd3l6cUVXUVlWaElBcG4rVVVVR1huK1FnbmJCYlBTcERjd0ExSDVUQ09FQUIvOE0KTGsvTExqTEpWeUFqRlhNNElhOEF1VE1yRUdHUGx5T29GWVREZml6dTVTd29RZ1Ewb3UvZkIvQTl1dHZDVUpmYQprSmlsbXFtSXE1eHlkS1IzUEJQTlllSkNLU05sdUg3VXJ1VjR4MDFwTjJKazNXT2VYQ0RRMEtsN1BsNmZNS3o0CmpYY0hQdzMyQkVDektYdVBSRkRqM3o3bE5sWXVkL1B1S0FQd3pDNnRkRTlQK1FDRnV1d1pGRGJ3N1hCVllPUTIKYTgzR3lwd3VBS1V3enFsN2pldTVyQklpdlcwWkIxRW12UXFXN21TdkhBTFZla0JVd2tBZjVyWnF5VHNhTW9NRwp6eDFQRm9aUWJ2ZjZSOW1Ud3JTSVFhVXV4T0hnd3dhWVd3SURBUUFCb3lBd0hqQU1CZ05WSFJNRUJUQURBUUgvCk1BNEdBMVVkRHdFQi93UUVBd0lCaGpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQWVuais2YWtxRmV4MUhybzgKZksxcUIwN1NnVjJhV0FnVkdLKzZOQXVvM0dlMzM0QjhNK2g5UjlSN3F1azBWSXY2M0UwWUxrMXVFRlBKTFMwbAo1YWdLU2JpZUdpU2FIMjBma3cvYTUvR2dNbW5XNGY1b1FBdzJxTzlJdEdWZXR3Y1luSjNTU25Hbm1CVUFkU01OCmNoWkZQNXRPbXdaekVJTWdOWjFiS0orQTVSdEIxekgvWVNuVWd5YmtUcDlHMjJzMEFCaksrVTNXdm9kbktYQjgKbVFnaHA0Z2F2S1BURzYzdlpEMWROcEp1a1htSnJHNXc4WU1Bcm43cEl1Q2xBOWFKc0RzNTNVMVI4WEROOGZmUworcCtXc2MwcTJxZ2o1Wk1pV3ltOXBwUjdCNDFiOVdXeTkzS0poNGU0UkRoTHpXUzl5RlhMRm9DdjBhbXJyMFJ6ClB4Um1BZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: cocktail-addon
  labels:
    k8s-app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020
    @INCLUDE input-kubernetes.conf
    @INCLUDE input-varlogmsg.conf
    @INCLUDE input-applog.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE filter-varlogmsg.conf
    @INCLUDE filter-applog.conf
    @INCLUDE output-elasticsearch.conf
  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
  input-varlogmsg.conf: |
    [INPUT]
        Name               tail
        Path               /var/log/messages
        Parser             syslog-rfc3164
        Tag                varlogmsg.*
        Refresh_Interval   10
        Mem_Buf_Limit      5MB
        Skip_Long_Lines    On
        Ignore_Older       1h
  input-applog.conf: |
    [INPUT]
        Name               tail
        Path               /applog/cri/logs/**/*.log
        Path_Key           filepath
        Parser             syslog-rfc3164
        Tag                app.*
        Tag_Regex          (app.applog.cri.logs.)(?<namespace_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?).(?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?).(?<log_kind>(log|prodlog)).(?<extra>([a-z0-9_.]*)).log$
        Refresh_Interval   10
        Mem_Buf_Limit      5MB
        Skip_Long_Lines    On
        Ignore_Older       1h
  filter-kubernetes.conf: |
    [FILTER]
        Name                record_modifier
        Match               kube.*
        Record              clusterid ${CLUSTER_ID}
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           Off
        #Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        #Regex_Parser        kube-custom
  filter-varlogmsg.conf: |
    [FILTER]
        Name                record_modifier
        Match               varlogmsg.*
        Record              clusterid ${CLUSTER_ID}
        Record              hostip ${HOST_IP}
        Record              kind SystemLog
  filter-applog.conf: |
    [FILTER]
        Name                record_modifier
        Match               app.*
        Record              clusterid ${CLUSTER_ID}
        Record              hostip ${HOST_IP}
        Record              kind ApplicationLog
  output-elasticsearch.conf: |
    [OUTPUT]
        Name            es
        Match           *
        Host            ${FLUENT_ELASTICSEARCH_HOST}
        Port            ${FLUENT_ELASTICSEARCH_PORT}
        Logstash_Format On
        Replace_Dots    On
        Retry_Limit     False
        HTTP_User       ${FLUENT_ELASTICSEARCH_USER}
        HTTP_Passwd     ${FLUENT_ELASTICSEARCH_PASSWD}
        tls             On
        tls.verify      Off
        tls.debug       1
        tls.ca_file     /secure/ca.crt
  parsers.conf: |
    [PARSER]
        Name   apache
        Format regex
        Regex  ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z
    [PARSER]
        Name   apache2
        Format regex
        Regex  ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^ ]*) +\S*)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z
    [PARSER]
        Name   apache_error
        Format regex
        Regex  ^\[[^ ]* (?<time>[^\]]*)\] \[(?<level>[^\]]*)\](?: \[pid (?<pid>[^\]]*)\])?( \[client (?<client>[^\]]*)\])? (?<message>.*)$
    [PARSER]
        Name   nginx
        Format regex
        Regex ^(?<remote>[^ ]*) (?<host>[^ ]*) (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z
    [PARSER]
        Name        k8s-nginx-ingress
        Format      regex
        Regex       ^(?<host>[^ ]*) - (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*) "(?<referer>[^\"]*)" "(?<agent>[^\"]*)" (?<request_length>[^ ]*) (?<request_time>[^ ]*) \[(?<proxy_upstream_name>[^ ]*)\] (\[(?<proxy_alternative_upstream_name>[^ ]*)\] )?(?<upstream_addr>[^ ]*) (?<upstream_response_length>[^ ]*) (?<upstream_response_time>[^ ]*) (?<upstream_status>[^ ]*) (?<reg_id>[^ ]*).*$
        Time_Key    time
        Time_Format %d/%b/%Y:%H:%M:%S %z
    [PARSER]
        Name   json
        Format json
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
    [PARSER]
        Name        docker-daemon
        Format      regex
        Regex       time="(?<time>[^ ]*)" level=(?<level>[^ ]*) msg="(?<msg>[^ ].*)"
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
    [PARSER]
        Name        syslog-rfc5424
        Format      regex
        Regex       ^\<(?<pri>[0-9]{1,5})\>1 (?<time>[^ ]+) (?<host>[^ ]+) (?<ident>[^ ]+) (?<pid>[-0-9]+) (?<msgid>[^ ]+) (?<extradata>(\[(.*?)\]|-)) (?<message>.+)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
        Time_Keep   On
    [PARSER]
        Name        syslog-rfc3164-local
        Format      regex
        Regex       ^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
        Time_Key    time
        Time_Format %b %d %H:%M:%S
    [PARSER]
        Name        syslog-rfc3164
        Format      regex
        Regex       /^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$/
        Time_Key    time
        Time_Format %b %d %H:%M:%S
        Time_Keep   On
    [PARSER]
        Name    mongodb
        Format  regex
        Regex   ^(?<time>[^ ]*)\s+(?<severity>\w)\s+(?<component>[^ ]+)\s+\[(?<context>[^\]]+)]\s+(?<message>.*?) *(?<ms>(\d+))?(:?ms)?$
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
        Time_Key time
    [PARSER]
        Name    envoy
        Format  regex
        Regex ^\[(?<start_time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)? (?<protocol>\S+)" (?<code>[^ ]*) (?<response_flags>[^ ]*) (?<bytes_received>[^ ]*) (?<bytes_sent>[^ ]*) (?<duration>[^ ]*) (?<x_envoy_upstream_service_time>[^ ]*) "(?<x_forwarded_for>[^ ]*)" "(?<user_agent>[^\"]*)" "(?<request_id>[^\"]*)" "(?<authority>[^ ]*)" "(?<upstream_host>[^ ]*)"
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
        Time_Keep   On
        Time_Key start_time
    [PARSER]
        Name cri
        Format regex
        Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<message>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
    [PARSER]
        Name    kube-custom
        Format  regex
        Regex   (?<tag>[^.]+)?\.?(?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-(?<docker_id>[a-z0-9]{64})\.log$
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: cocktail-addon
  labels:
    k8s-app: fluent-bit
spec:
  selector:
    matchLabels:
      k8s-app: fluent-bit
  template:
    metadata:
      labels:
        k8s-app: fluent-bit
    spec:
      serviceAccountName: fluent-bit
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - operator: "Exists"
        effect: "NoExecute"
      - operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:1.5.3
        imagePullPolicy: Always
        ports:
          - containerPort: 2020
        env:
        - name: FLUENT_ELASTICSEARCH_USER
          valueFrom:
            secretKeyRef:
              name: fluent-bit
              key: es-username
        - name: FLUENT_ELASTICSEARCH_PASSWD
          valueFrom:
            secretKeyRef:
              name: fluent-bit
              key: es-password
        - name: FLUENT_ELASTICSEARCH_HOST
          value: "hdcard-es.acloud.run"
          #value: "elasticsearch.cocktail-addon.svc"
        - name: FLUENT_ELASTICSEARCH_PORT
          value: "443"
          #value: "9200"
        - name: CLUSTER_ID
          value: "play-apps10-cluster"
        - name: HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        volumeMounts:
        - name: config-volume
          mountPath: /fluent-bit/etc/
        - name: datadocker
          mountPath: /prod/cri/docker
          #mountPath: /data/docker
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: secret-volume
          mountPath: /secure/ca.crt
          subPath: ca.crt
      terminationGracePeriodSeconds: 10
      volumes:
      - name: config-volume
        configMap:
          name: fluent-bit-config
      - name: varlog
        hostPath:
          path: /var/log
      - name: datadocker
        hostPath:
          path: /prod/cri/docker
          #path: /data/docker
      - name: varlibdockercontainers
        hostPath:
          path: /prod/cri/docker/containers
          #path: /data/docker/containers
          #path: /var/lib/docker/containers
      - name: secret-volume
        secret:
          secretName: fluent-bit
